"""Curated NSE research watchlist; edit this list to add or remove securities."""

SYMBOLS = [f'{ticker}.NS' for ticker in (
    'RELIANCE', 'TCS', 'INFY', 'HDFCBANK', 'ICICIBANK', 'SBIN', 'ITC', 'LT',
    'BEL', 'HAL', 'BHARTIARTL', 'AXISBANK', 'KOTAKBANK', 'BAJFINANCE',
    'HINDUNILVR', 'NESTLEIND', 'ASIANPAINT', 'MARUTI', 'M&M', 'TMPV',
    'TATASTEEL', 'JSWSTEEL', 'SUNPHARMA', 'DRREDDY', 'CIPLA', 'HCLTECH',
    'WIPRO', 'TECHM', 'TITAN', 'ULTRACEMCO', 'POWERGRID', 'NTPC', 'ONGC',
    'COALINDIA', 'ADANIPORTS', 'INDIGO', 'DMART', 'TRENT', 'EICHERMOT',
    'BAJAJFINSV', 'BPCL', 'GRASIM', 'HINDALCO', 'APOLLOHOSP', 'DIVISLAB',
    'BRITANNIA', 'HEROMOTOCO', 'SHRIRAMFIN', 'SBILIFE', 'HDFCLIFE',
)]
